### ISSUE TITLE
运行h2workerpy报错

### ISSUE THREAD

**Issue by xiongjie1207** [fanchy/h2engine#2]
运行h2workerpy报错

**Comment by xiongjie1207** [comment]
重新修改了代码，在smart_ptr.h加入一下代码
SharedPtr(const SharedPtr& p):
            m_dest_ptr(p.get()),
            m_ref_data(p.ger_ref_count())
    {
        if (nullptr != m_dest_ptr)
        {
            m_ref_data->m_ref_count.inc();
            m_ref_data->m_weak_ref_count.inc();
        }
    }

**Comment by fanchy** [comment]
已修复，谢谢！
